server:
  name: "dev-user"
  addr: "0.0.0.0:8080"
zap:
  debugFileName: "/logs/debug/pro-debug.log"
  infoFileName: "/logs/info/pro-info.log"
  warnFileName: "/logs/error/pro-error.log"
  maxSize: 500,
  maxAge: 28,
  MaxBackups: 3
redis:
  host: "redis7"
  port: 6379
  password: ""
  db: 0
grpc:
  addr: "0.0.0.0:8881"
  name: "user"
  version: "1.0.0"
  weight: 2
etcd:
  addrs:
    - "etcd3:2379"
mysql:
  username: root
  password: 123456
  host: 127.0.0.1
  port: 3306
  db: ms_project