server:
  name: "dev-api"
  addr: "127.0.0.1:80"
zap:
  debugFileName: "C:\\Pro\\Golang\\msDevelopment\\logs\\debug\\project-debug.log"
  infoFileName: "C:\\Pro\\Golang\\msDevelopment\\logs\\info\\project-info.log"
  warnFileName: "C:\\Pro\\Golang\\msDevelopment\\logs\\error\\project-error.log"
  maxSize: 500,
  maxAge: 28,
  MaxBackups: 3
etcd:
  addrs:
    - "127.0.0.1:2379"