server:
  name: "dev-api"
  addr: "127.0.0.1:8889"
zap:
  debugFileName: "logs/debug/pro-debug.log"
  infoFileName: "logs/info/pro-info.log"
  warnFileName: "logs/error/pro-error.log"
  maxSize: 500,
  maxAge: 28,
  MaxBackups: 3
etcd:
  addrs:
    - "127.0.0.1:2379"